FROM ubuntu:latest

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y python3 python3-pip

# If pip shows "externally managed", remove this file first
RUN rm -f /usr/lib/python*/EXTERNALLY-MANAGED

RUN pip3 install flask

WORKDIR /app
COPY ./api.py /app/api.py

EXPOSE 5252

CMD ["python3", "/app/api.py"]
